# Generated by Django 2.2.7 on 2019-12-02 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Discount', models.FloatField(blank=True, null=True)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(default='default.png', upload_to='')),
                ('Stock', models.IntegerField(default=1)),
                ('slug', models.SlugField()),
                ('ProductType', models.CharField(choices=[('T', 'Technology'), ('C', 'Comedy'), ('A', 'Adventure'), ('H', 'Horror'), ('R', 'Romance'), ('O', 'Other'), ('M', 'Mystery')], max_length=1)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=0)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Product')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('CardID', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('ProductID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='items.Product')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalQuantity', models.IntegerField(default=0)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
