# Generated by Django 2.2.7 on 2019-11-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to=''),
        ),
    ]
