# Generated by Django 2.2.7 on 2019-11-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
