# Generated by Django 2.2.7 on 2019-11-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20191121_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='noproducts',
            field=models.IntegerField(default=1),
        ),
    ]
