# Generated by Django 2.2.7 on 2019-11-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_noproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Discount', models.FloatField(blank=True, null=True)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(default='default.png', upload_to='')),
                ('Stock', models.IntegerField(default=1)),
                ('Slug', models.SlugField()),
                ('ProductType', models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport Wear'), ('O', 'Outwear')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
