# Generated by Django 2.2.7 on 2019-11-22 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0009_auto_20191121_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Product'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
