# Generated by Django 2.2.7 on 2019-11-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20191122_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='CartID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='TransactionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
