# Generated by Django 2.2.7 on 2019-11-22 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0011_auto_20191122_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Quantity',
            new_name='TotalQuantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ProductID',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('ProductID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='items.Product')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
